export * from './instances'
export { addClassnameToElement } from './addClassnameToElement'
export { createElementWithClassName } from './createElementWithClassName'
export { addCarImage } from './addCarImage'
export { generateNameCar } from './generateNameCar'
export * from './constants'
export { carsList } from './carsList'
export * from './sessionStorage'
export { createWinnerRow } from './createWinnerRow'
export { startAnimation } from './startAnimation'
export { gotoPage } from './gotoPage'